"""Initial migration

Revision ID: b4714aaab316
Revises:
Create Date: 2022-11-03 09:23:44.942134

"""
from alembic import op
from datetime import date
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4714aaab316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genders = op.create_table(
        'genders',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('biology', sa.String(length=6), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    users = op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('gender_id', sa.Integer(), nullable=False),
        sa.Column('birthday', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'measurements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('bmi', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_measurements_timestamp'),
        'measurements',
        ['timestamp'],
        unique=False
    )
    op.bulk_insert(genders, [
        {'id': 1, 'biology': 'MALE'},
        {'id': 2, 'biology': 'FEMALE'},
    ])
    op.bulk_insert(users, [
        {'id': 1, 'gender_id': 2, 'birthday': date(2010, 2, 26)}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('users')
    op.drop_table('genders')
    # ### end Alembic commands ###
